RAWDATA_DIR = '/staging/as/skchoudh/re-ribo-datasets/ASM276v2/'
OUT_DIR = '/staging/as/skchoudh/re-ribo-analysis/ASM276v2/'
GENOME_FASTA = '/home/qcb-panasas/skchoudh/genomes/ASM276v2/fasta/Plasmodium_falciparum.ASM276v2.dna.toplevel.fa'
CHROM_SIZES = '/home/qcb-panasas/skchoudh/genomes/ASM276v2/fasta/Plasmodium_falciparum.ASM276v2.dna.toplevel.sizes'
STAR_INDEX = '/home/qcb-panasas/skchoudh/genomes/ASM276v2/star_annotated_ribopod'
GTF_VERSION = 'v46'
GTF = '/home/qcb-panasas/skchoudh/genomes/ASM276v2/annotation/Plasmodium_falciparum.ASM276v2.46.gtf'
GENE_BED = '/home/qcb-panasas/skchoudh/github_projects/riboraptor/riboraptor/annotation/ASM276v2/v46/gene.bed.gz'
STAR_CODON_BED = '/home/qcb-panasas/skchoudh/github_projects/riboraptor/riboraptor/annotation/ASM276v2/v46/start_codon.bed.gz'
STOP_CODON_BED = '/home/qcb-panasas/skchoudh/github_projects/riboraptor/riboraptor/annotation/ASM276v2/v46/stop_codon.bed.gz'
CDS_BED = '/home/qcb-panasas/skchoudh/github_projects/riboraptor/riboraptor/annotation/ASM276v2/v46/cds.bed.gz'
UTR5_BED = '/home/qcb-panasas/skchoudh/github_projects/riboraptor/riboraptor/annotation/ASM276v2/v46/utr5.bed.gz'
UTR3_BED = '/home/qcb-panasas/skchoudh/github_projects/riboraptor/riboraptor/annotation/ASM276v2/v46/utr3.bed.gz'
INTRON_BED = '/home/qcb-panasas/skchoudh/github_projects/riboraptor/riboraptor/annotation/ASM276v2/v46/intron.bed.gz'
ORIENTATIONS = ['5prime', '3prime']
STRANDS = ['pos', 'neg', 'combined']
FRAGMENT_LENGTHS =  range(18, 39)
RIBOTRICER_ANNOTATION_PREFIX = '/home/cmb-06/as/skchoudh/genomes/ASM276v2/ribotricer_v46_annotation_longest'
