RAWDATA_DIR = '/staging/as/skchoudh/re-ribo-datasets/BDGP6/SRP033366'
OUT_DIR = '/staging/as/skchoudh/re-ribo-analysis/BDGP6/SRP033366'
GENOME_FASTA = '/home/qcb-panasas/skchoudh/genomes/BDGP6/fasta/Drosophila_melanogaster.BDGP6.22.dna.toplevel.fa'
CHROM_SIZES = '/home/qcb-panasas/skchoudh/genomes/BDGP6/fasta/Drosophila_melanogaster.BDGP6.22.dna.toplevel.sizes'
STAR_INDEX = '/home/qcb-panasas/skchoudh/genomes/BDGP6/star_annotated_ribopod'
GTF_VERSION = 'v96'
GTF = '/home/qcb-panasas/skchoudh/genomes/BDGP6/annotation/Drosophila_melanogaster.BDGP6.22.96.gtf'
GENE_BED = '/home/qcb-panasas/skchoudh/github_projects/riboraptor/riboraptor/annotation/BDGP6/v96/gene.bed.gz'
STAR_CODON_BED = '/home/qcb-panasas/skchoudh/github_projects/riboraptor/riboraptor/annotation/BDGP6/v96/start_codon.bed.gz'
STOP_CODON_BED = '/home/qcb-panasas/skchoudh/github_projects/riboraptor/riboraptor/annotation/BDGP6/v96/stop_codon.bed.gz'
CDS_BED = '/home/qcb-panasas/skchoudh/github_projects/riboraptor/riboraptor/annotation/BDGP6/v96/cds.bed.gz'
UTR5_BED = '/home/qcb-panasas/skchoudh/github_projects/riboraptor/riboraptor/annotation/BDGP6/v96/utr5.bed.gz'
UTR3_BED = '/home/qcb-panasas/skchoudh/github_projects/riboraptor/riboraptor/annotation/BDGP6/v96/utr3.bed.gz'
INTRON_BED = '/home/qcb-panasas/skchoudh/github_projects/riboraptor/riboraptor/annotation/BDGP6/v96/intron.bed.gz'
ORIENTATIONS = ['5prime', '3prime']
STRANDS = ['pos', 'neg', 'combined']
FRAGMENT_LENGTHS =  range(18, 39)
RIBOTRICER_ANNOTATION_PREFIX = '/home/cmb-06/as/skchoudh/genomes/BDGP6/ribotricer_v96_annotation_longest'
