RAWDATA_DIR = '/staging/as/skchoudh/re-ribo-datasets/Epr1/'
OUT_DIR = '/staging/as/skchoudh/re-ribo-analysis/Epr1/'
GENOME_FASTA = '/home/cmb-06/as/skchoudh/genomes/Epr1/fasta/Plasmodium_falciparum.EPr1.dna.toplevel.fa'
CHROM_SIZES = '/home/cmb-06/as/skchoudh/genomes/Epr1/fasta/Plasmodium_falciparum.EPr1.dna.toplevel.sizes'
STAR_INDEX = '/home/cmb-06/as/skchoudh/genomes/Epr1/star_annotated_ribopod'
GTF_VERSION = 'v44'
GTF = '/home/cmb-06/as/skchoudh/genomes/Epr1/annotation/Plasmodium_falciparum.EPr1.44.gtf'
GENE_BED = '/home/cmb-06/as/skchoudh/github_projects/riboraptor/riboraptor/annotation/Epr1/v44/gene.bed.gz'
STAR_CODON_BED = '/home/cmb-06/as/skchoudh/github_projects/riboraptor/riboraptor/annotation/Epr1/v44/start_codon.bed.gz'
STOP_CODON_BED = '/home/cmb-06/as/skchoudh/github_projects/riboraptor/riboraptor/annotation/Epr1/v44/stop_codon.bed.gz'
CDS_BED = '/home/cmb-06/as/skchoudh/github_projects/riboraptor/riboraptor/annotation/Epr1/v44/cds.bed.gz'
UTR5_BED = '/home/cmb-06/as/skchoudh/github_projects/riboraptor/riboraptor/annotation/Epr1/v44/utr5.bed.gz'
UTR3_BED = '/home/cmb-06/as/skchoudh/github_projects/riboraptor/riboraptor/annotation/Epr1/v44/utr3.bed.gz'
INTRON_BED = '/home/cmb-06/as/skchoudh/github_projects/riboraptor/riboraptor/annotation/Epr1/v44/intron.bed.gz'
ORIENTATIONS = ['5prime', '3prime']
STRANDS = ['pos', 'neg', 'combined']
FRAGMENT_LENGTHS =  range(18, 39)
RIBOTRICER_ANNOTATION_PREFIX = '/home/cmb-06/as/skchoudh/genomes/Epr1/ribotricer_v44_annotation_longest'
