RAWDATA_DIR = '/staging/as/skchoudh/re-ribo-datasets/JGI_4.2/SRP033369'
OUT_DIR = '/staging/as/skchoudh/re-ribo-analysis/JGI_4.2/SRP033369'
GENOME_FASTA = '/home/cmb-panasas2/skchoudh/genomes/JGI_4.2/fasta/Xenopus_tropicalis.JGI_4.2.dna.toplevel.fa'
CHROM_SIZES = '/home/cmb-panasas2/skchoudh/genomes/JGI_4.2/fasta/Xenopus_tropicalis.JGI_4.2.dna.toplevel.sizes'
STAR_INDEX = '/home/cmb-panasas2/skchoudh/genomes/JGI_4.2/star_annotated_ribopod'
GTF_VERSION = 'v96'
GTF = '/home/cmb-panasas2/skchoudh/genomes/JGI_4.2/annotation/Xenopus_tropicalis.JGI_4.2.96.gtf'
GENE_BED = '/home/cmb-panasas2/skchoudh/github_projects/riboraptor/riboraptor/annotation/JGI_4.2/v96/gene.bed.gz'
STAR_CODON_BED = '/home/cmb-panasas2/skchoudh/github_projects/riboraptor/riboraptor/annotation/JGI_4.2/v96/start_codon.bed.gz'
STOP_CODON_BED = '/home/cmb-panasas2/skchoudh/github_projects/riboraptor/riboraptor/annotation/JGI_4.2/v96/stop_codon.bed.gz'
CDS_BED = '/home/cmb-panasas2/skchoudh/github_projects/riboraptor/riboraptor/annotation/JGI_4.2/v96/cds.bed.gz'
UTR5_BED = '/home/cmb-panasas2/skchoudh/github_projects/riboraptor/riboraptor/annotation/JGI_4.2/v96/utr5.bed.gz'
UTR3_BED = '/home/cmb-panasas2/skchoudh/github_projects/riboraptor/riboraptor/annotation/JGI_4.2/v96/utr3.bed.gz'
INTRON_BED = '/home/cmb-panasas2/skchoudh/github_projects/riboraptor/riboraptor/annotation/JGI_4.2/v96/intron.bed.gz'
ORIENTATIONS = ['5prime', '3prime']
STRANDS = ['pos', 'neg', 'combined']
FRAGMENT_LENGTHS =  range(18, 39)
RIBOTRICER_ANNOTATION_PREFIX = '/home/cmb-06/as/skchoudh/genomes/JGI_4.2/ribotricer_v96_annotation_longest'
