RAWDATA_DIR = '/staging/as/skchoudh/re-ribo-datasets/mm10/SRP076551'
OUT_DIR = '/staging/as/skchoudh/re-ribo-analysis/mm10/SRP076551'
GENOME_FASTA = '/home/qcb-panasas/skchoudh/genomes/mm10/fasta/Mus_musculus.GRCm38.dna.primary_assembly.fa'
CHROM_SIZES = '/home/qcb-panasas/skchoudh/genomes/mm10/fasta/Mus_musculus.GRCm38.dna.primary_assembly.sizes'
STAR_INDEX = '/home/qcb-panasas/skchoudh/genomes/mm10/star_annotated_ribopod'
GTF_VERSION = 'v96'
GTF = '/home/qcb-panasas/skchoudh/genomes/mm10/annotation/Mus_musculus.GRCm38.96.chr_patch_hapl_scaff.gtf'
GENE_BED = '/home/qcb-panasas/skchoudh/github_projects/riboraptor/riboraptor/annotation/mm10/v96/gene.bed.gz'
STAR_CODON_BED = '/home/qcb-panasas/skchoudh/github_projects/riboraptor/riboraptor/annotation/mm10/v96/start_codon.bed.gz'
STOP_CODON_BED = '/home/qcb-panasas/skchoudh/github_projects/riboraptor/riboraptor/annotation/mm10/v96/stop_codon.bed.gz'
CDS_BED = '/home/qcb-panasas/skchoudh/github_projects/riboraptor/riboraptor/annotation/mm10/v96/cds.bed.gz'
UTR5_BED = '/home/qcb-panasas/skchoudh/github_projects/riboraptor/riboraptor/annotation/mm10/v96/utr5.bed.gz'
UTR3_BED = '/home/qcb-panasas/skchoudh/github_projects/riboraptor/riboraptor/annotation/mm10/v96/utr3.bed.gz'
INTRON_BED = '/home/qcb-panasas/skchoudh/github_projects/riboraptor/riboraptor/annotation/mm10/v96/intron.bed.gz'
ORIENTATIONS = ['5prime', '3prime']
STRANDS = ['pos', 'neg', 'combined']
FRAGMENT_LENGTHS =  range(18, 39)
RIBOTRICER_ANNOTATION_PREFIX = '/home/cmb-06/as/skchoudh/genomes/mm10/ribotricer_v96_annotation_longest'
