RAWDATA_DIR = '/staging/as/skchoudh/re-ribo-datasets/TryBruApr2005chr11/SRP041705'
OUT_DIR = '/staging/as/skchoudh/re-ribo-analysis/TryBruApr2005chr11/SRP041705'
GENOME_FASTA = '/home/cmb-panasas2/skchoudh/genomes/TryBru_Apr2005_chr11/fasta/Trypanosoma_brucei.TryBru_Apr2005_chr11.dna.toplevel.fa'
CHROM_SIZES = '/home/cmb-panasas2/skchoudh/genomes/TryBru_Apr2005_chr11/fasta/Trypanosoma_brucei.TryBru_Apr2005_chr11.dna.toplevel.sizes'
STAR_INDEX = '/home/cmb-panasas2/skchoudh/genomes/TryBru_Apr2005_chr11/star_annotated_ribopod'
GTF_VERSION = 'v44'
GTF = '/home/cmb-panasas2/skchoudh/genomes/TryBru_Apr2005_chr11/annotation/Trypanosoma_brucei.TryBru_Apr2005_chr11.44.gtf'
GENE_BED = '/home/cmb-panasas2/skchoudh/github_projects/riboraptor/riboraptor/annotation/TryBru_Apr2005_chr11/v44/gene.bed.gz'
STAR_CODON_BED = '/home/cmb-panasas2/skchoudh/github_projects/riboraptor/riboraptor/annotation/TryBru_Apr2005_chr11/v44/start_codon.bed.gz'
STOP_CODON_BED = '/home/cmb-panasas2/skchoudh/github_projects/riboraptor/riboraptor/annotation/TryBru_Apr2005_chr11/v44/stop_codon.bed.gz'
CDS_BED = '/home/cmb-panasas2/skchoudh/github_projects/riboraptor/riboraptor/annotation/TryBru_Apr2005_chr11/v44/cds.bed.gz'
UTR5_BED = '/home/cmb-panasas2/skchoudh/github_projects/riboraptor/riboraptor/annotation/TryBru_Apr2005_chr11/v44/utr5.bed.gz'
UTR3_BED = '/home/cmb-panasas2/skchoudh/github_projects/riboraptor/riboraptor/annotation/TryBru_Apr2005_chr11/v44/utr3.bed.gz'
INTRON_BED = '/home/cmb-panasas2/skchoudh/github_projects/riboraptor/riboraptor/annotation/TryBru_Apr2005_chr11/v44/intron.bed.gz'
ORIENTATIONS = ['5prime', '3prime']
STRANDS = ['pos', 'neg', 'combined']
FRAGMENT_LENGTHS =  range(18, 39)
RIBOTRICER_ANNOTATION_PREFIX = '/home/cmb-06/as/skchoudh/genomes/TryBru_Apr2005_chr11/ribotricer_v44_annotation_longest'
