RAWDATA_DIR = '/staging/as/skchoudh/re-ribo-datasets/WBcel235/SRP049414'
OUT_DIR = '/staging/as/skchoudh/re-ribo-analysis/WBcel235/SRP049414'
GENOME_FASTA = '/home/cmb-06/as/skchoudh/genomes/WBcel235/fasta/Caenorhabditis_elegans.WBcel235.dna.toplevel.fa'
CHROM_SIZES = '/home/cmb-06/as/skchoudh/genomes/WBcel235/fasta/Caenorhabditis_elegans.WBcel235.dna.toplevel.sizes'
STAR_INDEX = '/home/cmb-06/as/skchoudh/genomes/WBcel235/star_annotated_ribopod'
GTF_VERSION = 'v96'
GTF = '/home/cmb-06/as/skchoudh/genomes/WBcel235/annotation/Caenorhabditis_elegans.WBcel235.96.gtf'
GENE_BED = '/home/cmb-06/as/skchoudh/github_projects/riboraptor/riboraptor/annotation/WBcel235/v96/gene.bed.gz'
STAR_CODON_BED = '/home/cmb-06/as/skchoudh/github_projects/riboraptor/riboraptor/annotation/WBcel235/v96/start_codon.bed.gz'
STOP_CODON_BED = '/home/cmb-06/as/skchoudh/github_projects/riboraptor/riboraptor/annotation/WBcel235/v96/stop_codon.bed.gz'
CDS_BED = '/home/cmb-06/as/skchoudh/github_projects/riboraptor/riboraptor/annotation/WBcel235/v96/cds.bed.gz'
UTR5_BED = '/home/cmb-06/as/skchoudh/github_projects/riboraptor/riboraptor/annotation/WBcel235/v96/utr5.bed.gz'
UTR3_BED = '/home/cmb-06/as/skchoudh/github_projects/riboraptor/riboraptor/annotation/WBcel235/v96/utr3.bed.gz'
INTRON_BED = '/home/cmb-06/as/skchoudh/github_projects/riboraptor/riboraptor/annotation/WBcel235/v96/intron.bed.gz'
ORIENTATIONS = ['5prime', '3prime']
STRANDS = ['pos', 'neg', 'combined']
FRAGMENT_LENGTHS =  range(18, 39)
RIBOTRICER_ANNOTATION_PREFIX = '/home/cmb-06/as/skchoudh/genomes/WBcel235/ribotricer_v96_annotation_longest'
